# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: despawn.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'despawn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdespawn.proto\x12\x07\x64\x65spawn\"^\n\x12\x44\x65spawnEnemyPacket\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t\x12\x0f\n\x07room_id\x18\x03 \x01(\t\x12\x12\n\ndespawn_id\x18\x04 \x01(\t\"^\n\x12\x44\x65spawnTowerPacket\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t\x12\x0f\n\x07room_id\x18\x03 \x01(\t\x12\x12\n\ndespawn_id\x18\x04 \x01(\t\"c\n\x17\x44\x65spawnProjectilePacket\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t\x12\x0f\n\x07room_id\x18\x03 \x01(\t\x12\x12\n\ndespawn_id\x18\x04 \x01(\t\"M\n\x11\x44\x65spawnPacketData\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65spawn_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'despawn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DESPAWNENEMYPACKET']._serialized_start=26
  _globals['_DESPAWNENEMYPACKET']._serialized_end=120
  _globals['_DESPAWNTOWERPACKET']._serialized_start=122
  _globals['_DESPAWNTOWERPACKET']._serialized_end=216
  _globals['_DESPAWNPROJECTILEPACKET']._serialized_start=218
  _globals['_DESPAWNPROJECTILEPACKET']._serialized_end=317
  _globals['_DESPAWNPACKETDATA']._serialized_start=319
  _globals['_DESPAWNPACKETDATA']._serialized_end=396
# @@protoc_insertion_point(module_scope)
