# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x04game\"F\n\x0fGameStatePacket\x12\"\n\x05state\x18\x01 \x01(\x0e\x32\x13.game.GameStateType\x12\x0f\n\x07room_id\x18\x02 \x01(\t*m\n\rGameStateType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nSTART_WAVE\x10\x01\x12\x0c\n\x08\x45ND_WAVE\x10\x02\x12\x10\n\x0cGAME_SUCCESS\x10\x03\x12\r\n\tGAME_FAIL\x10\x04\x12\x10\n\x0c\x46ORCE_TIMEUP\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMESTATETYPE']._serialized_start=92
  _globals['_GAMESTATETYPE']._serialized_end=201
  _globals['_GAMESTATEPACKET']._serialized_start=20
  _globals['_GAMESTATEPACKET']._serialized_end=90
# @@protoc_insertion_point(module_scope)
