# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spawn.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spawn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bspawn.proto\x12\x05spawn\"Z\n\x10SpawnEnemyPacket\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t\x12\x0f\n\x07room_id\x18\x03 \x01(\t\x12\x10\n\x08spawn_id\x18\x04 \x01(\t\"Z\n\x10SpawnTowerPacket\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t\x12\x0f\n\x07room_id\x18\x03 \x01(\t\x12\x10\n\x08spawn_id\x18\x04 \x01(\t\"_\n\x15SpawnProjectilePacket\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t\x12\x0f\n\x07room_id\x18\x03 \x01(\t\x12\x10\n\x08spawn_id\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spawn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPAWNENEMYPACKET']._serialized_start=22
  _globals['_SPAWNENEMYPACKET']._serialized_end=112
  _globals['_SPAWNTOWERPACKET']._serialized_start=114
  _globals['_SPAWNTOWERPACKET']._serialized_end=204
  _globals['_SPAWNPROJECTILEPACKET']._serialized_start=206
  _globals['_SPAWNPROJECTILEPACKET']._serialized_end=301
# @@protoc_insertion_point(module_scope)
